### ISSUE TITLE
Missing string translation in views/templates/front/mailalerts-account.tpl

### ISSUE THREAD

**Issue by fdelprete** [PrestaShop/ps_emailalerts#12]
At line 37 of the tpl views/templates/front/mailalerts-account.tpl you have the translation
`{l s='No mail alerts yet.' d='Modules.Mailalerts.Shop'}`

You cannot translate that string in the PrestaShop BO.

**Comment by khouloudbelguith** [comment]
Hi @fdelprete,

This issue should be fixed in this ticket: https://github.com/PrestaShop/PrestaShop/issues/9697
Some strings in some module don't exist.

Best regards, Khouloud
