### ISSUE TITLE
(2.1.1) Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by BenTen** [PrestaShop/ps_emailalerts#16]
Hello,

With the version 2.1.1, in BO, when I save the setting, I get this error.
```
Warning on line 205 in file ../modules/ps_emailalerts/ps_emailalerts.php
[2] count(): Parameter must be an array or an object that implements Countable
```

**Comment by khouloudbelguith** [comment]
Hi @BenTen,

Thanks for your report.
I manage to reproduce the issue with PS1.7.5.0 & the ps_emailalerts v2.1.1.
![image](https://user-images.githubusercontent.com/16067358/52260266-ce1c4a00-2925-11e9-8baf-a55438c562e3.png)
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
Thanks!

**Comment by matks** [comment]
Hi @BenTen are you running php7.2 ?

**Comment by khouloudbelguith** [comment]
@matks, in my case, yes I'm running php7.2.
Thanks!

**Comment by khouloudbelguith** [comment]
Hi, I tried with PS1.7.5.0, ps_emailalerts v2.1.1 & PHP7.0 => OK.
Thanks!

**Comment by BenTen** [comment]
@matks Yes, 7.2

**Comment by rblaurin** [comment]
Was this fixed in #18?

**Comment by rblaurin** [comment]
@khouloudbelguith, PR #18 was merged and it fixes this issue. Maybe this issue could be closed?

**Comment by matteolavaggi** [comment]
(1/1) ContextErrorExceptionWarning: count(): Parameter must be an array or an object that implements Countable
--
in Cart.php line 61
at Cart->getPackageShippingCost(62, true, object(Country), null, 9)in Carrier.php line 758
at CarrierCore::getCarriersForOrder(9, array(3), object(Cart), array())in Carrier.php line 1555
at CarrierCore::getAvailableCarrierList(object(Product), 0, '269', 1, object(Cart))in Cart.php line 2411
at CartCore->getPackageList(false)in Cart.php line 2624
at CartCore->getDeliveryOptionList(null)in Cart.php line 3181
at CartCore->getDeliveryOption(null, false, false)in Cart.php line 3254
at CartCore->getTotalShippingCost(null, true)in Fees.php line 81
at Fees->processCalculation(object(Cart), object(CartRowCollection), '2', null)in Calculator.php line 294
at Calculator->calculateFees('2')in Calculator.php line 129
at Calculator->processCalculation('2')in Cart.php line 1973
at CartCore->getOrderTotal(false)in CartPresenter.php line 327
at CartPresenter->present(object(Cart))in FrontController.php line 490
at FrontControllerCore->assignGeneralPurposeVariables()in FrontController.php line 548
at FrontControllerCore->initContent()in IndexController.php line 37
at IndexControllerCore->initContent()in Controller.php line 291
at ControllerCore->run()in Dispatcher.php line 387
at Dispatcher->dispatch()in index.php line 28

**Comment by khouloudbelguith** [comment]
@matteolavaggi, different issue as reported here: https://github.com/PrestaShop/PrestaShop/issues/11065#issuecomment-523458600

Thanks!

**Comment by ivo71** [comment]
I have the same error on 1.7.6.1 under php 7.2 and when I change php to 7.0 there is no error.

**Comment by BenTen** [comment]
@ivo71 Did you update the module?

Did you try this fix?
https://github.com/PrestaShop/ps_emailalerts/pull/18/commits/7a9c367289b1b8315c6c59b148cbefac97576bc0
