### ISSUE TITLE
Module not finished

### ISSUE THREAD

**Issue by davidglezz** [PrestaShop/ps_emailalerts#35]
It was noted that there are unused parts of the module, inherited from old versions and copy-paste code from other modules.

https://github.com/PrestaShop/ps_emailalerts/search?q=favorite&unscoped_q=favorite

**Comment by matks** [comment]
Hi @davidglezz indeed there are some work that could be done to improve this module but right now PrestaShop maintainers focus is on other topics.

I close this issue as it's unlikely we'll find extra time on our side to deal with this and it does not seem critical. Feel free to invest some of your time on it if it's important for you 😉  .
