### ISSUE TITLE
[ps_emailalerts] {total_shipping} Display with tax instead of without tax

### ISSUE THREAD

**Issue by Betafer** [PrestaShop/ps_emailalerts#46]
<img width="528" alt="Schermata 2020-03-11 alle 23 34 32" src="https://user-images.githubusercontent.com/5024055/76471511-252b0300-63f3-11ea-9bfd-c343e6a22733.png">
<img width="801" alt="Schermata 2020-03-11 alle 23 34 23" src="https://user-images.githubusercontent.com/5024055/76471515-265c3000-63f3-11ea-9fc0-58511f35fdc2.png">

As images, one is in the BO and one in Email, in email {total_shipping}  in incorrect (without tax)

PS: 1.7.6.3

**Comment by Betafer** [comment]
Solved by changing {total_shipping} to {total_shipping_tax_excl} in all email (so is not a module problem)
but i think this would change when i shop owner set show price with tax in the backoffice

**Comment by matks** [comment]
> Solved by changing {total_shipping} to {total_shipping_tax_excl} in all email (so is not a module problem)

Thank you for telling us about it 😉
