### ISSUE TITLE
Button Translation

### ISSUE THREAD

**Issue by HartLarsson** [PrestaShop/ps_emailalerts#48]
![image](https://user-images.githubusercontent.com/16102074/78708872-14e34680-7913-11ea-899e-c0eb89ae6f8e.png)

Is possible to translate in other languages then English the button?
Seems is not supported.

Thanks

**Comment by dali-rajab** [comment]
It's a bug, I have created a PR https://github.com/PrestaShop/ps_emailalerts/pull/49 to fix not only that button, but also many other translations, and I am waiting for the maintainers to merge that PR. Have a nice day !

**Comment by matks** [comment]
https://github.com/PrestaShop/ps_emailalerts/pull/49 was merged so I believe we can mark this as solved :)
