### ISSUE TITLE
How to resend a new order notification to the seller?

### ISSUE THREAD

**Issue by kerstar** [PrestaShop/ps_emailalerts#55]
Hello,

I have a minor problem.

Due to a failure on the mail server side, notifications of new orders could not be sent.
The mail server crash has been fixed and I thought that I would simply be able to manually resend the seller about new orders, but I don't see this option anywhere.

How do I resend a new order notification to the seller?

Can anyone tell me what code and where to add, so as to add a button on the order card to resend the notification to the seller for a given order?

Regards,

**Comment by matks** [comment]
Hello, we use GitHub issues only to discuss about bugs and new features for the PrestaShop project.

Follow https://devdocs.prestashop.com/1.7/faq/i-need-help/ to find the very best places to get an answer
