### ISSUE TITLE
Useless usage of "count" in postProcess

### ISSUE THREAD

**Issue by voxTeam** [PrestaShop/ps_emailalerts#56]
Hi,

What is the point of "count" at this line : 

https://github.com/PrestaShop/ps_emailalerts/blob/dadce9e048d0be19a6097dc74fb4b7b3393ce159/ps_emailalerts.php#L205

It's raising a warning and we have a "!empty" before.

Regards,

**Comment by PierreRambaud** [comment]
I see no interest in having this count :thinking: 

an is_array is better

**Comment by matks** [comment]
Hi everybody if you have suggestions to improve the module code, feel free to submit a PR 😉
