### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by Peter-Liska** [PrestaShop/ps_emailalerts#75]
It is impossible add release v2.2.1 to PrestaShop.

Repair is required in this way:
1. Unpack code.
2. Rename directory simple to "ps_emailalerts"
3. Pack.

Please produce the following releases correctly so that they can be added without additional effort.

**Comment by matks** [comment]
Hi @Peter-Liska where did you download ps_emailalerts v2.2.1 ?

**Comment by Peter-Liska** [comment]
> Hi @Peter-Liska where did you download ps_emailalerts v2.2.1 ?

https://github.com/PrestaShop/ps_emailalerts/releases

**Comment by matks** [comment]
The files `Source code (zip)` and `Source code (targ.gz)` are not ready-to-be-used ZIP archives of the module. These are files that are automatically created by GitHub, basically GitHub just provides a ready-for-download version of the repository. But it's the source code, not an artifact that can be run directly.

There has never been ready-to-be-used ZIP archives on https://github.com/PrestaShop/ps_emailalerts/releases . If you check all the releases, there is never a ZIP archive with name `ps_emailalerts`

The distribution channel for this module is to download it through PrestaShop Addons API. PrestaShop Addons API serve ready-to-be-used ZIP archives. The most user-friendly way to do it is through your PrestaShop back-office.
