### ISSUE TITLE
total_tax_paid is wrong with discount

### ISSUE THREAD

**Issue by neoteknic** [PrestaShop/ps_emailalerts#8]
Total tax paid is wrong with a discount.
It show tax without discount.
ps_emailalert.php line 407

**Comment by Hlavtox** [comment]
@neoteknic Made a PR with a fix: https://github.com/PrestaShop/ps_emailalerts/pull/29

**Comment by khouloudbelguith** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/16227
